### PR TITLE
Add basic main menu

### PR DESCRIPTION
**Pull request by WellHatchedOne**
Add basic main menu

### CODE REVIEW

**Comment by drentawc** [comment]
Approved

**Comment by ianbrobin** [comment]
This is 2 commits. You should squash then

**Comment by WellHatchedOne** [comment]
> This is 2 commits. You should squash then

Good catch. Will make sure to squash and merge.

**Comment by ianbrobin** [comment]
LGTM

**Review by ianbrobin — COMMENTED** [review]
LGTM

**Pull request merged**
